version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eulabs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["sh", "-c", "sleep 10 && /app/main"]
